/*
SQLyog Ultimate v8.32 
MySQL - 5.7.14-log : Database - LICY_TEST
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
CREATE DATABASE /*!32312 IF NOT EXISTS*/`LICY_TEST` /*!40100 DEFAULT CHARACTER SET utf8 */;

USE `LICY_TEST`;

/*Table structure for table `T_REFUND_TRANS` */

DROP TABLE IF EXISTS `T_REFUND_TRANS`;

CREATE TABLE `T_REFUND_TRANS` (
  `ID` int(11) NOT NULL,
  `REFUND_NAME` varchar(32) DEFAULT NULL,
  `REFUND_FEE_AMT` varchar(32) DEFAULT NULL,
  `REFUND_ORDER_TYPR` varchar(32) NOT NULL DEFAULT 'NON_REAL_TIME' COMMENT '退款订单类型:NON_REAL_TIME(默认值)非实时退款、REAL_TIME:实时退款',
  `TEST` varchar(16) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Data for the table `T_REFUND_TRANS` */

insert  into `T_REFUND_TRANS`(`ID`,`REFUND_NAME`,`REFUND_FEE_AMT`,`REFUND_ORDER_TYPR`,`TEST`) values (1,'licy','530','','HI,WORLD'),(2,'YAge','345','','HI,WORLD'),(4,'lic','457','','SORRY');

/*Table structure for table `T_USER` */

DROP TABLE IF EXISTS `T_USER`;

CREATE TABLE `T_USER` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '用户编号',
  `USER_NAME` varchar(64) DEFAULT NULL COMMENT '用户名称',
  `PASSWORD` varchar(64) DEFAULT NULL COMMENT '登录密码',
  `USER_TYPE` varchar(4) DEFAULT NULL COMMENT '用户类型',
  `CREATE_TIME` timestamp NULL DEFAULT NULL COMMENT '创建时间',
  `UPDATE_TIME` timestamp NULL DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;

/*Data for the table `T_USER` */

insert  into `T_USER`(`ID`,`USER_NAME`,`PASSWORD`,`USER_TYPE`,`CREATE_TIME`,`UPDATE_TIME`) values (1,'Jinmu','14qed34j45h4401$mr90B92','1','2017-07-20 19:18:05','2017-07-20 19:18:05');

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
